[2022-12-16 08:16:18,919] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.get_last_id scheduled__2022-12-15T17:44:00+00:00 [queued]>
[2022-12-16 08:16:19,177] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.get_last_id scheduled__2022-12-15T17:44:00+00:00 [queued]>
[2022-12-16 08:16:19,177] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-16 08:16:19,177] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-16 08:16:19,177] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-16 08:16:19,607] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_last_id> on 2022-12-15 17:44:00+00:00
[2022-12-16 08:16:19,730] {standard_task_runner.py:52} INFO - Started process 17013 to run task
[2022-12-16 08:16:19,914] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'prepare_data', 'get_last_id', 'scheduled__2022-12-15T17:44:00+00:00', '--job-id', '189', '--raw', '--subdir', 'DAGS_FOLDER/prepare_data.py', '--cfg-path', '/tmp/tmp4os4x3du', '--error-file', '/tmp/tmpbrzopmqh']
[2022-12-16 08:16:19,964] {standard_task_runner.py:80} INFO - Job 189: Subtask get_last_id
[2022-12-16 08:16:21,698] {task_command.py:369} INFO - Running <TaskInstance: prepare_data.get_last_id scheduled__2022-12-15T17:44:00+00:00 [running]> on host 8e2f65ec4c74
[2022-12-16 08:16:23,737] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=prepare_data
AIRFLOW_CTX_TASK_ID=get_last_id
AIRFLOW_CTX_EXECUTION_DATE=2022-12-15T17:44:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-15T17:44:00+00:00
[2022-12-16 08:16:23,916] {base.py:68} INFO - Using connection ID 'gp_conn' for task execution.
[2022-12-16 08:16:24,671] {python.py:173} INFO - Done. Returned value was: None
[2022-12-16 08:16:24,995] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=prepare_data, task_id=get_last_id, execution_date=20221215T174400, start_date=20221216T081618, end_date=20221216T081624
[2022-12-16 08:16:25,548] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-16 08:16:26,177] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
