[2022-12-12 18:40:56,147] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.get_last_id scheduled__2022-11-28T18:29:00+00:00 [queued]>
[2022-12-12 18:40:56,238] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.get_last_id scheduled__2022-11-28T18:29:00+00:00 [queued]>
[2022-12-12 18:40:56,243] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 18:40:56,245] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-12 18:40:56,247] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 18:40:56,389] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_last_id> on 2022-11-28 18:29:00+00:00
[2022-12-12 18:40:56,415] {standard_task_runner.py:52} INFO - Started process 879 to run task
[2022-12-12 18:40:56,469] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'prepare_data', 'get_last_id', 'scheduled__2022-11-28T18:29:00+00:00', '--job-id', '329', '--raw', '--subdir', 'DAGS_FOLDER/prepare_data.py', '--cfg-path', '/tmp/tmpsauv494w', '--error-file', '/tmp/tmpuiee10sb']
[2022-12-12 18:40:56,478] {standard_task_runner.py:80} INFO - Job 329: Subtask get_last_id
[2022-12-12 18:40:56,693] {task_command.py:369} INFO - Running <TaskInstance: prepare_data.get_last_id scheduled__2022-11-28T18:29:00+00:00 [running]> on host cfea470654c7
[2022-12-12 18:40:57,131] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=prepare_data
AIRFLOW_CTX_TASK_ID=get_last_id
AIRFLOW_CTX_EXECUTION_DATE=2022-11-28T18:29:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-28T18:29:00+00:00
[2022-12-12 18:40:57,167] {base.py:68} INFO - Using connection ID 'postgres_default' for task execution.
[2022-12-12 18:40:57,247] {python.py:173} INFO - Done. Returned value was: None
[2022-12-12 18:40:57,294] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=prepare_data, task_id=get_last_id, execution_date=20221128T182900, start_date=20221212T184056, end_date=20221212T184057
[2022-12-12 18:40:57,376] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-12 18:40:57,541] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
